//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraControl.ServerTest.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/CameraControl.Service")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICameraService")]
    public interface ICameraService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICameraService/GetData", ReplyAction="http://tempuri.org/ICameraService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICameraService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ICameraService/GetDataUsingDataContractResponse")]
        CameraControl.ServerTest.ServiceReference1.CompositeType GetDataUsingDataContract(CameraControl.ServerTest.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICameraService/Initialize", ReplyAction="http://tempuri.org/ICameraService/InitializeResponse")]
        void Initialize();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICameraService/Capture", ReplyAction="http://tempuri.org/ICameraService/CaptureResponse")]
        void Capture();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICameraService/TakePhotoAsBase64String", ReplyAction="http://tempuri.org/ICameraService/TakePhotoAsBase64StringResponse")]
        string TakePhotoAsBase64String(int timeoutSeconds, int resizeWidth, int resizeHight, int rotation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICameraServiceChannel : CameraControl.ServerTest.ServiceReference1.ICameraService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CameraServiceClient : System.ServiceModel.ClientBase<CameraControl.ServerTest.ServiceReference1.ICameraService>, CameraControl.ServerTest.ServiceReference1.ICameraService {
        
        public CameraServiceClient() {
        }
        
        public CameraServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CameraServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CameraServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CameraServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public CameraControl.ServerTest.ServiceReference1.CompositeType GetDataUsingDataContract(CameraControl.ServerTest.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public void Initialize() {
            base.Channel.Initialize();
        }
        
        public void Capture() {
            base.Channel.Capture();
        }
        
        public string TakePhotoAsBase64String(int timeoutSeconds, int resizeWidth, int resizeHight, int rotation) {
            return base.Channel.TakePhotoAsBase64String(timeoutSeconds, resizeWidth, resizeHight, rotation);
        }
    }
}
